In [ ]:
import pandas as pd
lyft_bike_data = pd.read_csv(r'lyft2.csv')
lyft_bike_data

       start_station_id end_station_id  ...     end_lng  member_casual
0                SF-R19         SF-R20  ... -122.427622         member
1                SF-A27       SF-F28-2  ... -122.400808         member
2                SF-P22         SF-I27  ... -122.402728         member
3                SF-S24       SF-S22-1  ... -122.420215         member
4                SF-N21         SF-N21  ... -122.426497         member
...                 ...            ...  ...         ...            ...
130532           SF-J29         SF-L22  ... -122.422047         member
130533           SF-J29       SF-J26-2  ... -122.407908         member
130534         SF-J23-1         SF-A19  ... -122.437215         casual
130535         SF-K22-2         SF-L22  ... -122.422248         member
130536         SF-J23-1         SF-L22  ... -122.422248         casual

[130537 rows x 7 columns]

In [ ]:
from google.colab import drive
from google.colab import files
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
lyft_bike_data = lyft_bike_data[lyft_bike_data["start_station_id"].notnull()]
lyft_bike_data = lyft_bike_data[lyft_bike_data["end_station_id"].notnull()]
lyft_bike_data

       start_station_id end_station_id  ...     end_lng  member_casual
0                SF-R19         SF-R20  ... -122.427622         member
1                SF-A27       SF-F28-2  ... -122.400808         member
2                SF-P22         SF-I27  ... -122.402728         member
3                SF-S24       SF-S22-1  ... -122.420215         member
4                SF-N21         SF-N21  ... -122.426497         member
...                 ...            ...  ...         ...            ...
130532           SF-J29         SF-L22  ... -122.422047         member
130533           SF-J29       SF-J26-2  ... -122.407908         member
130534         SF-J23-1         SF-A19  ... -122.437215         casual
130535         SF-K22-2         SF-L22  ... -122.422248         member
130536         SF-J23-1         SF-L22  ... -122.422248         casual

[130537 rows x 7 columns]

In [ ]:
lyft_bike_data = lyft_bike_data.drop_duplicates(subset=["start_station_id","end_station_id"])
#lyft_bike_data = lyft_bike_data.drop_duplicates(subset=["end_station_id"])
lyft_bike_data

       start_station_id end_station_id  ...     end_lng  member_casual
0                SF-R19         SF-R20  ... -122.427622         member
1                SF-A27       SF-F28-2  ... -122.400808         member
2                SF-P22         SF-I27  ... -122.402728         member
3                SF-S24       SF-S22-1  ... -122.420215         member
4                SF-N21         SF-N21  ... -122.426497         member
...                 ...            ...  ...         ...            ...
130502           SF-E20       SF-J26-2  ... -122.408183         casual
130516           SF-M30       SF-M22-1  ... -122.420506         casual
130517         SF-C28-1         SF-L22  ... -122.422187         casual
130522           SF-L24         SF-J15  ... -122.453110         member
130526         SF-N20-1       SF-J26-2  ... -122.408223         member

[28670 rows x 7 columns]

In [ ]:
vertex = lyft_bike_data.drop(['member_casual'],axis=1)
vertex = vertex.reset_index(drop=True)
vertex.to_csv('ffinal_graphs_data.csv')
vertex
files.download('ffinal_graphs_data.csv')